-- MySQL Script generated by MySQL Workbench
-- Mon Mar 24 23:18:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Pokeapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pokeapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pokeapi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Pokeapi` ;

-- -----------------------------------------------------
-- Table `Pokeapi`.`ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`ability` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pokeapi`.`move`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`move` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `type_id` INT NULL DEFAULT NULL,
  `power` INT NULL DEFAULT NULL,
  `accuracy` INT NULL DEFAULT NULL,
  `times_of_use` INT NULL DEFAULT NULL,
  `damage_area` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  INDEX `type_id` (`type_id` ASC) VISIBLE,
  CONSTRAINT `move_ibfk_1`
    FOREIGN KEY (`type_id`)
    REFERENCES `Pokeapi`.`type` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pokeapi`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`pokemon` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `height` INT NULL DEFAULT NULL,
  `weight` INT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `evolution_stage` INT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pokeapi`.`pokemon_ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`pokemon_ability` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pokemon_id` INT NOT NULL,
  `ability_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pokemon` (`pokemon_id` ASC) VISIBLE,
  INDEX `fk_ability` (`ability_id` ASC) VISIBLE,
  CONSTRAINT `fk_ability`
    FOREIGN KEY (`ability_id`)
    REFERENCES `Pokeapi`.`ability` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_pokemon`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `Pokeapi`.`pokemon` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pokeapi`.`pokemon_evolution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`pokemon_evolution` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `base_pokemon_id` INT NOT NULL,
  `evolved_pokemon_id` INT NOT NULL,
  `evolution_trigger` VARCHAR(100) NULL DEFAULT NULL,
  `level_required` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_pokemon_evolution` (`base_pokemon_id` ASC, `evolved_pokemon_id` ASC) VISIBLE,
  INDEX `fk_evolved_pokemon` (`evolved_pokemon_id` ASC) VISIBLE,
  CONSTRAINT `fk_base_pokemon`
    FOREIGN KEY (`base_pokemon_id`)
    REFERENCES `Pokeapi`.`pokemon` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_evolved_pokemon`
    FOREIGN KEY (`evolved_pokemon_id`)
    REFERENCES `Pokeapi`.`pokemon` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pokeapi`.`pokemon_move`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`pokemon_move` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pokemon_id` INT NOT NULL,
  `move_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_pokemon_move` (`pokemon_id` ASC, `move_id` ASC) VISIBLE,
  INDEX `fk_move` (`move_id` ASC) VISIBLE,
  CONSTRAINT `fk_move`
    FOREIGN KEY (`move_id`)
    REFERENCES `Pokeapi`.`move` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_pokemon_move`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `Pokeapi`.`pokemon` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pokeapi`.`pokemon_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`pokemon_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pokemon_id` INT NOT NULL,
  `type_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pokemon_type_pokemon` (`pokemon_id` ASC) VISIBLE,
  CONSTRAINT `fk_pokemon_type_pokemon`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `Pokeapi`.`pokemon` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Pokeapi`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokeapi`.`type` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


